#!/bin/bash
echo "Creating common env  file"
cat <<EOT >/home/ubuntu/.env
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_USER=${POSTGRES_USER}
NODE_ENV=production
NEXT_PUBLIC_MJW_SERVICE_HOST=localhost
NEXT_PUBLIC_MJW_SERVICE_PORT=8080
EOT
